[package]
name = "CCIPTokenPool"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
ChainlinkCCIP = { local = "../../ccip" }

[addresses]
ccip = "0x1000"
ccip_token_pool = "0x2000"
burn_mint_token_pool = "0x2001"
mcms = "0x4000"
mcms_register_entrypoints = "0x4001"
local_token = "0x9000"
