[package]
name = "CCIPTokenPool"
edition = "2024.beta"

[dependencies]
ChainlinkCCIP = { local = "../../ccip" }

[addresses]
ccip = "_"
ccip_router = "_"
ccip_token_pool = "_"

[dev-addresses]
ccip = "0x1000"
ccip_router = "0x1001"
ccip_token_pool = "0x2000"
