[package]
name = "ManagedTokenPool"
edition = "2024"

[addresses]
managed_token_pool = "0x0"

[dependencies]
ChainlinkCCIP = { local = "../../ccip" }
ChainlinkManyChainMultisig = { local = "../../../mcms/mcms" }
ManagedToken = { local = "../../managed_token" }
