[package]
name = "ManagedTokenPool"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[addresses]
ccip = "_"
ccip_token_pool = "_"
managed_token_pool = "_"
managed_token = "_"
managed_token_coin_metadata = "_"
mcms = "_"
mcms_owner = "_"

[dev-addresses]
ccip = "0x1000"
ccip_token_pool = "0x2000"
managed_token_pool = "0x2001"
managed_token = "0x9000"
managed_token_coin_metadata = "0x9001"
mcms = "0x4000"
mcms_owner = "0x4010"

[dependencies]
ChainlinkCCIP = { local = "../../ccip" }
CCIPTokenPool = { local = "../token_pool" }
ManagedToken = { local = "../../managed_token"}
