[package]
name = "ManagedTokenPool"
edition = "2024"

[addresses]
ccip = "_"
ccip_token_pool = "_"
managed_token_pool = "_"
managed_token = "_"
mcms = "_"
mcms_owner = "_"

[dev-addresses]
ccip = "0x1000"
ccip_token_pool = "0x2000"
managed_token_pool = "0x2001"
managed_token = "0x9000"
mcms = "0x4000"
mcms_owner = "0x4010"

[dependencies]
ChainlinkCCIP = { local = "../../ccip" }
CCIPTokenPool = { local = "../token_pool" }
ManagedToken = { local = "../../managed_token"}
ChainlinkManyChainMultisig = { local = "../../../mcms/mcms" }
