version: "3"

tasks:
  default:
    desc: "Run go mod tidy in all modules"
    cmds:
      - for:
          matrix:
            MODULE: [".", "./integration-tests", "./deployment", "./scripts"]
        cmd: cd {{ .ITEM.MODULE }} && go mod tidy
      - task: modgraph

  modgraph:
    desc: "Run go mod graph in all modules and writes to go.md"
    cmd: ./scripts/modgraph.sh > go.md
