package bind

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// PublishedTOMLEntry represents a publication entry for a specific environment
type PublishedTOMLEntry struct {
	ChainID           string
	PublishedAt       string // The on-chain address of the published package
	OriginalID        string // The address of the first version of the package
	Version           int
	ToolchainVersion  string
	UpgradeCapability string
}

// EphemeralPubEntry represents an entry in the ephemeral publication file (Pub.<env>.toml)
type EphemeralPubEntry struct {
	Source      string // Can be local path, git URL, or root
	PublishedAt string
	OriginalID  string
	UpgradeCap  string
	Version     int // Package version number
}

// EphemeralPubFile represents the structure of Pub.<env>.toml files
type EphemeralPubFile struct {
	BuildEnv  string
	ChainID   string
	Published []EphemeralPubEntry
}

// WritePublishedTOML writes a Published.toml file for a package at the given directory.
// This is used to make a dependency resolvable when building packages that depend on it.
//
// Parameters:
//   - packageDir: The directory containing the package (where Published.toml will be written)
//   - environment: The environment name (e.g., "testnet", "mainnet", "local")
//   - chainID: The chain identifier (first 8 chars of chain ID hash)
//   - publishedAt: The on-chain address where the package is published
//   - originalID: The original package ID (for v1, same as publishedAt)
//   - version: The package version number
func WritePublishedTOML(packageDir, environment, chainID, publishedAt, originalID string, version int) error {
	publishedTomlPath := filepath.Join(packageDir, "Published.toml")

	// Normalize addresses to have 0x prefix
	publishedAt = normalizeAddress(publishedAt)
	originalID = normalizeAddress(originalID)

	content := fmt.Sprintf(`# Generated by chainlink-sui bindings
# This file contains metadata about published versions of this package
# This file is auto-generated for dependency resolution

[published.%s]
chain-id = "%s"
published-at = "%s"
original-id = "%s"
version = %d
`, environment, chainID, publishedAt, originalID, version)

	if err := os.WriteFile(publishedTomlPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("failed to write Published.toml at %s: %w", publishedTomlPath, err)
	}

	return nil
}

// WriteEphemeralPubFile writes an ephemeral publication file (Pub.<env>.toml) for test publishing.
// This file tracks publications of the package and its dependencies for ephemeral environments.
//
// Parameters:
//   - filePath: The full path to the ephemeral pub file
//   - buildEnv: The build environment (e.g., "testnet", "mainnet")
//   - chainID: The actual chain ID of the network being published to
//   - entries: List of published package entries
func WriteEphemeralPubFile(filePath, buildEnv, chainID string, entries []EphemeralPubEntry) error {
	var sb strings.Builder

	sb.WriteString("# Generated by chainlink-sui bindings\n")
	sb.WriteString("# This file contains metadata from ephemeral publications\n")
	sb.WriteString("# This file should NOT be committed to source control\n\n")
	sb.WriteString(fmt.Sprintf("build-env = \"%s\"\n", buildEnv))
	sb.WriteString(fmt.Sprintf("chain-id = \"%s\"\n\n", chainID))

	for _, entry := range entries {
		sb.WriteString("[[published]]\n")

		// Format source field based on dependency type
		// Sui CLI expects inline table format for local dependencies: { local = "path" }
		if strings.HasPrefix(entry.Source, "/") || strings.HasPrefix(entry.Source, ".") {
			sb.WriteString(fmt.Sprintf("source = { local = \"%s\" }\n", entry.Source))
		} else if entry.Source == "root" {
			sb.WriteString("source = \"root\"\n")
		} else {
			// Default to local format for any other path
			sb.WriteString(fmt.Sprintf("source = { local = \"%s\" }\n", entry.Source))
		}

		sb.WriteString(fmt.Sprintf("published-at = \"%s\"\n", normalizeAddress(entry.PublishedAt)))
		sb.WriteString(fmt.Sprintf("original-id = \"%s\"\n", normalizeAddress(entry.OriginalID)))
		version := entry.Version
		if version == 0 {
			version = 1 // Default to version 1 for new packages
		}
		sb.WriteString(fmt.Sprintf("version = %d\n", version))
		if entry.UpgradeCap != "" {
			sb.WriteString(fmt.Sprintf("upgrade-cap = \"%s\"\n", normalizeAddress(entry.UpgradeCap)))
		}
		sb.WriteString("\n")
	}

	if err := os.WriteFile(filePath, []byte(sb.String()), 0o644); err != nil {
		return fmt.Errorf("failed to write ephemeral pub file at %s: %w", filePath, err)
	}

	return nil
}

// AppendToEphemeralPubFile adds a new entry to an existing ephemeral pub file
// If the file doesn't exist, it creates a new one
func AppendToEphemeralPubFile(filePath, buildEnv, chainID string, entry EphemeralPubEntry) error {
	// Check if file exists
	existingContent, err := os.ReadFile(filePath)
	if err != nil {
		if os.IsNotExist(err) {
			// Create new file with single entry
			return WriteEphemeralPubFile(filePath, buildEnv, chainID, []EphemeralPubEntry{entry})
		}
		return fmt.Errorf("failed to read existing pub file: %w", err)
	}

	// Append the new entry
	var sb strings.Builder
	sb.Write(existingContent)

	// Ensure there's a newline before the new entry
	if len(existingContent) > 0 && existingContent[len(existingContent)-1] != '\n' {
		sb.WriteString("\n")
	}

	sb.WriteString("[[published]]\n")
	// Format source field based on dependency type
	// Sui CLI expects inline table format for local dependencies: { local = "path" }
	if strings.HasPrefix(entry.Source, "/") || strings.HasPrefix(entry.Source, ".") {
		sb.WriteString(fmt.Sprintf("source = { local = \"%s\" }\n", entry.Source))
	} else if entry.Source == "root" {
		sb.WriteString("source = \"root\"\n")
	} else {
		// Default to local format for any other path
		sb.WriteString(fmt.Sprintf("source = { local = \"%s\" }\n", entry.Source))
	}
	sb.WriteString(fmt.Sprintf("published-at = \"%s\"\n", normalizeAddress(entry.PublishedAt)))
	sb.WriteString(fmt.Sprintf("original-id = \"%s\"\n", normalizeAddress(entry.OriginalID)))
	version := entry.Version
	if version == 0 {
		version = 1 // Default to version 1 for new packages
	}
	sb.WriteString(fmt.Sprintf("version = %d\n", version))
	if entry.UpgradeCap != "" {
		sb.WriteString(fmt.Sprintf("upgrade-cap = \"%s\"\n", normalizeAddress(entry.UpgradeCap)))
	}
	sb.WriteString("\n")

	if err := os.WriteFile(filePath, []byte(sb.String()), 0o644); err != nil {
		return fmt.Errorf("failed to append to pub file: %w", err)
	}

	return nil
}

// UpdatePublishedTOMLForUpgrade updates an existing Published.toml file for a package upgrade.
// This updates the published-at address and increments the version.
func UpdatePublishedTOMLForUpgrade(packageDir, environment, chainID, newPublishedAt, originalID string, newVersion int, upgradeCap string) error {
	publishedTomlPath := filepath.Join(packageDir, "Published.toml")

	// Normalize addresses
	newPublishedAt = normalizeAddress(newPublishedAt)
	originalID = normalizeAddress(originalID)
	upgradeCap = normalizeAddress(upgradeCap)

	content := fmt.Sprintf(`# Generated by chainlink-sui bindings
# This file contains metadata about published versions of this package
# This file is auto-generated for dependency resolution

[published.%s]
chain-id = "%s"
published-at = "%s"
original-id = "%s"
version = %d
upgrade-capability = "%s"
`, environment, chainID, newPublishedAt, originalID, newVersion, upgradeCap)

	if err := os.WriteFile(publishedTomlPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("failed to write Published.toml at %s: %w", publishedTomlPath, err)
	}

	return nil
}

// normalizeAddress ensures the address has 0x prefix and is properly formatted
func normalizeAddress(addr string) string {
	if addr == "" {
		return addr
	}
	addr = strings.TrimSpace(addr)
	if !strings.HasPrefix(addr, "0x") {
		return "0x" + addr
	}
	return addr
}

// RemovePublishedTOML removes the Published.toml file from a package directory
// This is useful when cleaning up temporary workspaces
func RemovePublishedTOML(packageDir string) error {
	publishedTomlPath := filepath.Join(packageDir, "Published.toml")
	if err := os.Remove(publishedTomlPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove Published.toml at %s: %w", publishedTomlPath, err)
	}
	return nil
}

// removePublishedEntry removes the entry for a specific environment from Published.toml
// This is needed when re-compiling a package (e.g., for upgrades) because
// 'sui client publish' refuses to publish if the package is already in Published.toml.
// The function preserves entries for other environments.
func removePublishedEntry(packageDir, environment string) error {
	publishedTomlPath := filepath.Join(packageDir, "Published.toml")

	content, err := os.ReadFile(publishedTomlPath)
	if err != nil {
		if os.IsNotExist(err) {
			// No Published.toml, nothing to remove
			return nil
		}
		return fmt.Errorf("failed to read Published.toml: %w", err)
	}

	lines := strings.Split(string(content), "\n")
	var newLines []string
	inTargetSection := false
	sectionHeader := fmt.Sprintf("[published.%s]", environment)

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Check if we're entering the target section
		if trimmed == sectionHeader {
			inTargetSection = true
			continue
		}

		// Check if we're entering a different section (ends the target section)
		if inTargetSection && strings.HasPrefix(trimmed, "[") {
			inTargetSection = false
		}

		// Skip lines in the target section
		if inTargetSection {
			continue
		}

		newLines = append(newLines, line)
	}

	newContent := strings.Join(newLines, "\n")

	// Only write if content changed
	if newContent != string(content) {
		if err := os.WriteFile(publishedTomlPath, []byte(newContent), 0o644); err != nil {
			return fmt.Errorf("failed to write Published.toml: %w", err)
		}
	}

	return nil
}

// EnsureEnvironmentInMoveToml ensures the [environments] section exists in Move.toml
// with the specified environment and chain ID
func EnsureEnvironmentInMoveToml(packageDir, environment, chainID string) error {
	moveTomlPath := filepath.Join(packageDir, "Move.toml")

	content, err := os.ReadFile(moveTomlPath)
	if err != nil {
		return fmt.Errorf("failed to read Move.toml: %w", err)
	}

	lines := strings.Split(string(content), "\n")
	inEnvSection := false
	envSectionExists := false
	envLineIdx := -1

	// First pass: find [environments] section and the environment line
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)

		if trimmed == "[environments]" {
			inEnvSection = true
			envSectionExists = true
			continue
		}

		if inEnvSection {
			// Check if we hit the next section
			if strings.HasPrefix(trimmed, "[") {
				inEnvSection = false
				break
			}

			// Check if this is the environment line we're looking for
			// Handle both `env = 'value'` and `env = "value"` formats with optional indentation
			if strings.HasPrefix(trimmed, environment+" = ") || strings.HasPrefix(trimmed, environment+"=") {
				envLineIdx = i
			}
		}
	}

	// Second pass: update or add the environment
	if envSectionExists {
		if envLineIdx != -1 {
			// Replace existing environment line, preserving any leading whitespace from the original
			originalLine := lines[envLineIdx]
			leadingSpace := originalLine[:len(originalLine)-len(strings.TrimLeft(originalLine, " \t"))]
			lines[envLineIdx] = fmt.Sprintf("%s%s = \"%s\"", leadingSpace, environment, chainID)
		} else {
			// Add new environment to existing section
			// Insert after [environments] line - find it first
			insertIdx := -1
			for i, line := range lines {
				if strings.TrimSpace(line) == "[environments]" {
					insertIdx = i + 1
					break
				}
			}
			if insertIdx != -1 {
				newLine := fmt.Sprintf("%s = \"%s\"", environment, chainID)
				// Insert the new line
				lines = append(lines[:insertIdx], append([]string{newLine}, lines[insertIdx:]...)...)
			}
		}
	} else {
		// Add new [environments] section - try to add it after [package] section
		// Some Sui CLI versions may be sensitive to section ordering
		insertIdx := -1
		for i, line := range lines {
			trimmed := strings.TrimSpace(line)
			// Insert before [addresses] or [dependencies] if they exist
			if trimmed == "[addresses]" || trimmed == "[dependencies]" {
				insertIdx = i
				break
			}
		}

		envLines := []string{"", "[environments]", fmt.Sprintf("%s = \"%s\"", environment, chainID)}

		if insertIdx != -1 {
			// Insert before [addresses] or [dependencies]
			newLines := make([]string, 0, len(lines)+len(envLines))
			newLines = append(newLines, lines[:insertIdx]...)
			newLines = append(newLines, envLines...)
			newLines = append(newLines, lines[insertIdx:]...)
			lines = newLines
		} else {
			// No [addresses] or [dependencies], add at the end
			if len(lines) > 0 && lines[len(lines)-1] != "" {
				lines = append(lines, "")
			}
			lines = append(lines, "[environments]", fmt.Sprintf("%s = \"%s\"", environment, chainID))
		}
	}

	newContent := strings.Join(lines, "\n")
	// Ensure file ends with newline
	if !strings.HasSuffix(newContent, "\n") {
		newContent += "\n"
	}

	// Only write if content changed
	if newContent != string(content) {
		f, err := os.OpenFile(moveTomlPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o644)
		if err != nil {
			return fmt.Errorf("failed to open Move.toml for writing: %w", err)
		}
		if _, err := f.WriteString(newContent); err != nil {
			f.Close()
			return fmt.Errorf("failed to write Move.toml: %w", err)
		}
		if err := f.Sync(); err != nil {
			f.Close()
			return fmt.Errorf("failed to sync Move.toml: %w", err)
		}
		f.Close()
	}

	return nil
}
