[package]
name = "BurnMintTokenPool"
edition = "2024"

[dependencies]
ChainlinkCCIP = { local = "../../ccip" }
ChainlinkManyChainMultisig = { local = "../../../mcms/mcms" }

[addresses]
burn_mint_token_pool = "0x0"
