[package]
name = "BurnMintTokenPool"
edition = "2024.beta"

[dependencies]
CCIPTokenPool = { local = "../token_pool" }

[addresses]
ccip = "_"
ccip_token_pool = "_"
burn_mint_token_pool = "_"
burn_mint_token_coin_metadata = "_"
mcms = "_"
mcms_owner = "_"

[dev-addresses]
ccip = "0x1000"
ccip_token_pool = "0x2000"
burn_mint_token_pool = "0x2001"
burn_mint_token_coin_metadata = "0x9000"
mcms = "0x4000"
mcms_owner = "0x4010"
