[package]
name = "ChainlinkManyChainMultisig"
edition = "2024"

[addresses]
mcms = "0x7dd8c89002aa29bd802da52b8b5dd92eed1d94b5a1daa6e9f80ae9599f656e8d"
mcms_owner = "0x0"

[dev-addresses]
mcms = "0x0"
mcms_owner = "0x4010"