[package]
name = "ChainlinkManyChainMultisig"
edition = "2024"

[dependencies]

[addresses]
mcms = "0x0"
mcms_owner = "0x0"

[dev-addresses]
mcms = "0x0"
mcms_owner = "0x4010"

[environments]
local = "4c78adac"