[package]
name = "ChainlinkCCIPOnramp"
edition = "2024"
published-at = "0x88a3b7110b01efca491198e92bb8e90d69bea0e60b920406028733a124ade06d"

[addresses]
ccip = "_"
ccip_onramp = "0x0"
mcms = "_"
mcms_owner = "_"

[dev-addresses]
ccip = "0x1000"
ccip_onramp = "0x1001"
mcms = "0x4000"
mcms_owner = "0x4010"

[dependencies]
ChainlinkCCIP = { local = "../ccip" }
ChainlinkManyChainMultisig = { local = "../../mcms/mcms" }
