[package]
name = "ChainlinkCCIPOnramp"
edition = "2024"

[addresses]
ccip_onramp = "0x0"

[dependencies]
ChainlinkCCIP = { local = "../ccip" }
ChainlinkManyChainMultisig = { local = "../../mcms/mcms" }
