[package]
name = "ChainlinkCCIPOnramp"
edition = "2024"

[addresses]
ccip = "_"
ccip_onramp = "_"
mcms = "_"
mcms_owner = "_"

[dev-addresses]
ccip = "0x1000"
ccip_onramp = "0x1001"
mcms = "0x4000"
mcms_owner = "0x4010"

[dependencies]
ChainlinkCCIP = { local = "../ccip" }
ChainlinkManyChainMultisig = { local = "../../mcms/mcms" }
