[package]
name = "ChainlinkCCIPOnramp"
edition = "2024"
published-at = "0x30e087460af8a8aacccbc218aa358cdcde8d43faf61ec0638d71108e276e2f1d"

[addresses]
ccip = "_"
ccip_onramp = "0x0"
mcms = "_"
mcms_owner = "_"

[dev-addresses]
ccip = "0x1000"
ccip_onramp = "0x1001"
mcms = "0x4000"
mcms_owner = "0x4010"

[dependencies]
ChainlinkCCIP = { local = "../ccip" }
ChainlinkManyChainMultisig = { local = "../../mcms/mcms" }
