[package]
name = "ChainlinkCCIPOnramp"
edition = "2024.beta"

[addresses]
ccip = "_"
ccip_onramp = "_"

[dev-addresses]
ccip = "0x1000"
ccip_onramp = "0x1001"

[dependencies]
ChainlinkCCIP = { local = "../ccip" }
