[package]
name = "counterB"
edition = "2024.beta"  
# # oldpkgID: 0xc77f80eabb68a17d5336647162a9cdd7885b738e8af28f14ce626e0bcdbc0e58
# published-at="0xa140cfff8f8679139373712876ed12e895492c2a1f6722c2dffa540e040bdcdd"

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/mainnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

  # [dependencies.counterA_old]
  #   local = "../counter_a_old"

  [dependencies.counterA]
    local = '../counter_a'
 
[addresses]
counter_b = "0x0"
counter_a = "_"
 