[package]
name = "ManagedTokenFaucet"
edition = "2024"

[dependencies]
ChainlinkManyChainMultisig = { local = "../../mcms/mcms" }
ManagedToken = { local = "../managed_token" }

[addresses]
managed_token_faucet = "0x0"
