[package]
name = "counterA"
edition = "2024" 
# oldPkgID: 0x477f04c2b5cb1e7a989d7a1ac37b23ebdd86e9588eb2f77d1acdab9a305e214d
# published-at="0x477f04c2b5cb1e7a989d7a1ac37b23ebdd86e9588eb2f77d1acdab9a305e214d"

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/mainnet'
    subdir = 'crates/sui-framework/packages/sui-framework'
 
 
[addresses]
counter_a = "0x0"
 
