[package]
name = "LockReleaseTokenPool"
edition = "2024"

[dependencies]
ChainlinkCCIP = { local = "../../ccip" }
ChainlinkManyChainMultisig = { local = "../../../mcms/mcms" }

[addresses]
ccip = "0x9de8a33d158e26f0b51f199da8be1a22e9755510b705cfb88230b257187da733"
lock_release_token_pool = "0x0"
mcms = "0x7dd8c89002aa29bd802da52b8b5dd92eed1d94b5a1daa6e9f80ae9599f656e8d"
mcms_owner = "0x4010"

[dev-addresses]
ccip = "0x1000"
mcms = "0x4000"
mcms_owner = "0x4010"
lock_release_token_pool = "0x2001"
