[package]
name = "LockReleaseTokenPool"
edition = "2024"

[dependencies]
ChainlinkCCIP = { local = "../../ccip" }
ChainlinkManyChainMultisig = { local = "../../../mcms/mcms" }

[addresses]
lock_release_token_pool = "0x0"
