
echo "Generating bindings for Move Sui contracts..."

# Build the bindings (add the path to contracts you want to generate bindings for)

# Test Package
go run bindgen/main.go --moveConfig ./contracts/test/ --input ./contracts/test/sources/counter.move --output ./bindings/generated/test/counter
go run bindgen/main.go --moveConfig ./contracts/test/ --input ./contracts/test/sources/complex.move --output ./bindings/generated/test/complex

# CCIP 
go run bindgen/main.go --moveConfig ./contracts/ccip/ccip --input ./contracts/ccip/ccip/sources/fee_quoter.move --output ./bindings/generated/ccip/ccip/fee_quoter --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common""
go run bindgen/main.go --moveConfig ./contracts/ccip/ccip --input ./contracts/ccip/ccip/sources/nonce_manager.move --output ./bindings/generated/ccip/ccip/nonce_manager --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common""
go run bindgen/main.go --moveConfig ./contracts/ccip/ccip --input ./contracts/ccip/ccip/sources/receiver_registry.move --output ./bindings/generated/ccip/ccip/receiver_registry --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common""
go run bindgen/main.go --moveConfig ./contracts/ccip/ccip --input ./contracts/ccip/ccip/sources/rmn_remote.move --output ./bindings/generated/ccip/ccip/rmn_remote --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common""
go run bindgen/main.go --moveConfig ./contracts/ccip/ccip --input ./contracts/ccip/ccip/sources/token_admin_registry.move --output ./bindings/generated/ccip/ccip/token_admin_registry --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common""

# CCIP - Onramp
go run bindgen/main.go --moveConfig ./contracts/ccip/ccip_onramp --input ./contracts/ccip/ccip_onramp/sources/onramp.move --output ./bindings/generated/ccip/ccip_onramp/onramp --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::NonceManagerCap="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::SourceTransferCap="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::TokenParams="github.com/smartcontractkit/chainlink-sui/bindings/common""
go run bindgen/main.go --moveConfig ./contracts/ccip/ccip_onramp --input ./contracts/ccip/ccip_onramp/sources/ownable.move --output ./bindings/generated/ccip/ccip_onramp/ownable --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::NonceManagerCap="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::SourceTransferCap="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::TokenParams="github.com/smartcontractkit/chainlink-sui/bindings/common""

# CCIP - Offramp
go run bindgen/main.go --moveConfig ./contracts/ccip/ccip_offramp --input ./contracts/ccip/ccip_offramp/sources/offramp.move --output ./bindings/generated/ccip/ccip_offramp/offramp --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::FeeQuoterCap="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::DestTransferCap="github.com/smartcontractkit/chainlink-sui/bindings/common""
go run bindgen/main.go --moveConfig ./contracts/ccip/ccip_offramp --input ./contracts/ccip/ccip_offramp/sources/ownable.move --output ./bindings/generated/ccip/ccip_offramp/ownable --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::FeeQuoterCap="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::DestTransferCap="github.com/smartcontractkit/chainlink-sui/bindings/common""

# CCIP - LINK
go run bindgen/main.go --moveConfig ./contracts/ccip/link_token --input ./contracts/ccip/link_token/sources/link_token.move --output ./bindings/generated/ccip/link_token/link_token

# CCIP - Managed Token
go run bindgen/main.go --moveConfig ./contracts/ccip/managed_token --input ./contracts/ccip/managed_token/sources/managed_token.move --output ./bindings/generated/ccip/managed_token/managed_token --externalStructs "ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::TokenState="github.com/smartcontractkit/chainlink-sui/bindings/common""

# CCIP - Token Pool
go run bindgen/main.go --moveConfig ./contracts/ccip/ccip_token_pools/token_pool --input ./contracts/ccip/ccip_token_pools/token_pool/sources/token_pool.move --output ./bindings/generated/ccip/ccip_token_pools/token_pool --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::TokenPoolState="github.com/smartcontractkit/chainlink-sui/bindings/common""

# CCIP - Lock Release Token Pool
go run bindgen/main.go --moveConfig ./contracts/ccip/ccip_token_pools/lock_release_token_pool --input ./contracts/ccip/ccip_token_pools/lock_release_token_pool/sources/lock_release_token_pool.move --output ./bindings/generated/ccip/ccip_token_pools/lock_release_token_pool --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::TokenParams="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::ReceiverParams="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::LockReleaseTokenPoolState="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnableState="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::TokenPoolState="github.com/smartcontractkit/chainlink-sui/bindings/common""

# CCIP - Burn Mint Token Pool
go run bindgen/main.go --moveConfig ./contracts/ccip/ccip_token_pools/burn_mint_token_pool --input ./contracts/ccip/ccip_token_pools/burn_mint_token_pool/sources/burn_mint_token_pool.move --output ./bindings/generated/ccip/ccip_token_pools/burn_mint_token_pool --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::TokenParams="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::ReceiverParams="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::BurnMintTokenPoolState="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnableState="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::TokenPoolState="github.com/smartcontractkit/chainlink-sui/bindings/common""

# CCIP - Managed Token Pool
go run bindgen/main.go --moveConfig ./contracts/ccip/ccip_token_pools/managed_token_pool --input ./contracts/ccip/ccip_token_pools/managed_token_pool/sources/managed_token_pool.move --output ./bindings/generated/ccip/ccip_token_pools/managed_token_pool --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::TokenParams="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::ReceiverParams="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::ManagedTokenPoolState="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnableState="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::TokenPoolState="github.com/smartcontractkit/chainlink-sui/bindings/common""

# CCIP Router
go run bindgen/main.go --moveConfig ./contracts/ccip/ccip_router --input ./contracts/ccip/ccip_router/sources/router.move --output ./bindings/generated/ccip/ccip_router/ --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common""

# MCMS
go run bindgen/main.go --moveConfig ./contracts/mcms/mcms --input ./contracts/mcms/mcms/sources/mcms.move --output ./bindings/generated/mcms/mcms --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common""
go run bindgen/main.go --moveConfig ./contracts/mcms/mcms --input ./contracts/mcms/mcms/sources/mcms_account.move --output ./bindings/generated/mcms/mcms_account --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common""
go run bindgen/main.go --moveConfig ./contracts/mcms/mcms --input ./contracts/mcms/mcms/sources/mcms_registry.move --output ./bindings/generated/mcms/mcms_registry --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common""
go run bindgen/main.go --moveConfig ./contracts/mcms/mcms --input ./contracts/mcms/mcms/sources/mcms_deployer.move --output ./bindings/generated/mcms/mcms_deployer --externalStructs "ccip::common::CCIPObjectRef="github.com/smartcontractkit/chainlink-sui/bindings/common",ccip::common::OwnerCap="github.com/smartcontractkit/chainlink-sui/bindings/common""

