[package]
name = "USDCTokenPool"
edition = "2024"

[dependencies]
CCIPTokenPool = { local = "../token_pool" }

# Circle CCTP Imports
MessageTransmitter = { local = "../../../vendored/circlefin/sui-cctp/packages/message_transmitter" }
TokenMessengerMinter = { local = "../../../vendored/circlefin/sui-cctp/packages/token_messenger_minter" }

[addresses]
ccip = "_"
ccip_token_pool = "_"
usdc_token_pool = "_"
usdc_coin_metadata_object_id = "_"
token_messenger_minter = "_"
token_messenger_minter_state = "_"
message_transmitter = "_"
message_transmitter_state = "_"
treasury = "_"
mcms = "_"
mcms_owner = "_"

[dev-addresses]
ccip = "0x1000"
ccip_token_pool = "0x2000"
usdc_token_pool = "0x2003"
usdc_coin_metadata_object_id = "0x9000"
token_messenger_minter = "0x31cc14d80c175ae39777c0238f20594c6d4869cfab199f40b69f3319956b8beb"
token_messenger_minter_state = "0x5252abd1137094ed1db3e0d75bc36abcd287aee4bc310f8e047727ef5682e7c2"
message_transmitter = "0x4931e06dce648b3931f890035bd196920770e913e43e45990b383f6486fdd0a5"
message_transmitter_state = "0x98234bd0fa9ac12cc0a20a144a22e36d6a32f7e0a97baaeaf9c76cdc6d122d2e"
treasury = "0x7170137d4a6431bf83351ac025baf462909bffe2877d87716374fb42b9629ebe"
mcms = "0x4000"
mcms_owner = "0x4010"
