[package]
name = "ChainlinkCCIPDummyReceiver"
edition = "2024.beta"

[addresses]
ccip = "_"
ccip_dummy_receiver = "_"

[dev-addresses]
ccip = "0x1000"
ccip_dummy_receiver = "0x3010"

[dependencies]
ChainlinkCCIP = { local = "../ccip" }