[package]
name = "ChainlinkCCIPDummyReceiver"
edition = "2024"

[addresses]
ccip = "0x5ef4b483da6644c84aa78eae4f51a9bfb1fb4554d5134ac98892e931fcbdd6bf"
ccip_dummy_receiver = "0x0"
mcms = "_"
mcms_owner = "_"

[dev-addresses]
ccip = "0x1000"
ccip_dummy_receiver = "0x3010"
mcms = "0x4000"
mcms_owner = "0x4010"

[dependencies]
ChainlinkCCIP = { local = "../ccip" }
