// Code generated by MockGen. DO NOT EDIT.
// Source: relayer/client/ptb_client.go
//
// Generated by this command:
//
//	mockgen -source=relayer/client/ptb_client.go -destination=relayer/client/mocks/mock_ptb_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	models "github.com/block-vision/sui-go-sdk/models"
	signer "github.com/block-vision/sui-go-sdk/signer"
	sui "github.com/block-vision/sui-go-sdk/sui"
	transaction "github.com/block-vision/sui-go-sdk/transaction"
	cache "github.com/patrickmn/go-cache"
	gomock "go.uber.org/mock/gomock"

	module_token_admin_registry "github.com/smartcontractkit/chainlink-sui/bindings/generated/ccip/ccip/token_admin_registry"
	client "github.com/smartcontractkit/chainlink-sui/relayer/client"
)

// MockSuiPTBClient is a mock of SuiPTBClient interface.
type MockSuiPTBClient struct {
	ctrl     *gomock.Controller
	recorder *MockSuiPTBClientMockRecorder
	isgomock struct{}
}

// MockSuiPTBClientMockRecorder is the mock recorder for MockSuiPTBClient.
type MockSuiPTBClientMockRecorder struct {
	mock *MockSuiPTBClient
}

// NewMockSuiPTBClient creates a new mock instance.
func NewMockSuiPTBClient(ctrl *gomock.Controller) *MockSuiPTBClient {
	mock := &MockSuiPTBClient{ctrl: ctrl}
	mock.recorder = &MockSuiPTBClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuiPTBClient) EXPECT() *MockSuiPTBClientMockRecorder {
	return m.recorder
}

// BlockByDigest mocks base method.
func (m *MockSuiPTBClient) BlockByDigest(ctx context.Context, txDigest string) (*client.SuiTransactionBlockResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockByDigest", ctx, txDigest)
	ret0, _ := ret[0].(*client.SuiTransactionBlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockByDigest indicates an expected call of BlockByDigest.
func (mr *MockSuiPTBClientMockRecorder) BlockByDigest(ctx, txDigest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockByDigest", reflect.TypeOf((*MockSuiPTBClient)(nil).BlockByDigest), ctx, txDigest)
}

// EstimateGas mocks base method.
func (m *MockSuiPTBClient) EstimateGas(ctx context.Context, txBytes string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateGas", ctx, txBytes)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateGas indicates an expected call of EstimateGas.
func (mr *MockSuiPTBClientMockRecorder) EstimateGas(ctx, txBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateGas", reflect.TypeOf((*MockSuiPTBClient)(nil).EstimateGas), ctx, txBytes)
}

// FinishPTBAndSend mocks base method.
func (m *MockSuiPTBClient) FinishPTBAndSend(ctx context.Context, txnSigner *signer.Signer, tx *transaction.Transaction, requestType client.TransactionRequestType) (client.SuiTransactionBlockResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishPTBAndSend", ctx, txnSigner, tx, requestType)
	ret0, _ := ret[0].(client.SuiTransactionBlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinishPTBAndSend indicates an expected call of FinishPTBAndSend.
func (mr *MockSuiPTBClientMockRecorder) FinishPTBAndSend(ctx, txnSigner, tx, requestType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishPTBAndSend", reflect.TypeOf((*MockSuiPTBClient)(nil).FinishPTBAndSend), ctx, txnSigner, tx, requestType)
}

// GetBlockById mocks base method.
func (m *MockSuiPTBClient) GetBlockById(ctx context.Context, checkpointId string) (models.CheckpointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockById", ctx, checkpointId)
	ret0, _ := ret[0].(models.CheckpointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockById indicates an expected call of GetBlockById.
func (mr *MockSuiPTBClientMockRecorder) GetBlockById(ctx, checkpointId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockById", reflect.TypeOf((*MockSuiPTBClient)(nil).GetBlockById), ctx, checkpointId)
}

// GetCCIPPackageID mocks base method.
func (m *MockSuiPTBClient) GetCCIPPackageID(ctx context.Context, offRampPackageID, signerAddress string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCCIPPackageID", ctx, offRampPackageID, signerAddress)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCCIPPackageID indicates an expected call of GetCCIPPackageID.
func (mr *MockSuiPTBClientMockRecorder) GetCCIPPackageID(ctx, offRampPackageID, signerAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCCIPPackageID", reflect.TypeOf((*MockSuiPTBClient)(nil).GetCCIPPackageID), ctx, offRampPackageID, signerAddress)
}

// GetCache mocks base method.
func (m *MockSuiPTBClient) GetCache() *cache.Cache {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCache")
	ret0, _ := ret[0].(*cache.Cache)
	return ret0
}

// GetCache indicates an expected call of GetCache.
func (mr *MockSuiPTBClientMockRecorder) GetCache() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCache", reflect.TypeOf((*MockSuiPTBClient)(nil).GetCache))
}

// GetCachedValue mocks base method.
func (m *MockSuiPTBClient) GetCachedValue(key string) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedValue", key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetCachedValue indicates an expected call of GetCachedValue.
func (mr *MockSuiPTBClientMockRecorder) GetCachedValue(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedValue", reflect.TypeOf((*MockSuiPTBClient)(nil).GetCachedValue), key)
}

// GetCachedValues mocks base method.
func (m *MockSuiPTBClient) GetCachedValues(keys []string) (map[string]any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedValues", keys)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetCachedValues indicates an expected call of GetCachedValues.
func (mr *MockSuiPTBClientMockRecorder) GetCachedValues(keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedValues", reflect.TypeOf((*MockSuiPTBClient)(nil).GetCachedValues), keys)
}

// GetClient mocks base method.
func (m *MockSuiPTBClient) GetClient() sui.ISuiAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient")
	ret0, _ := ret[0].(sui.ISuiAPI)
	return ret0
}

// GetClient indicates an expected call of GetClient.
func (mr *MockSuiPTBClientMockRecorder) GetClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockSuiPTBClient)(nil).GetClient))
}

// GetCoinsByAddress mocks base method.
func (m *MockSuiPTBClient) GetCoinsByAddress(ctx context.Context, address string) ([]models.CoinData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoinsByAddress", ctx, address)
	ret0, _ := ret[0].([]models.CoinData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoinsByAddress indicates an expected call of GetCoinsByAddress.
func (mr *MockSuiPTBClientMockRecorder) GetCoinsByAddress(ctx, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoinsByAddress", reflect.TypeOf((*MockSuiPTBClient)(nil).GetCoinsByAddress), ctx, address)
}

// GetLatestPackageId mocks base method.
func (m *MockSuiPTBClient) GetLatestPackageId(ctx context.Context, packageId, module string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestPackageId", ctx, packageId, module)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestPackageId indicates an expected call of GetLatestPackageId.
func (mr *MockSuiPTBClientMockRecorder) GetLatestPackageId(ctx, packageId, module any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestPackageId", reflect.TypeOf((*MockSuiPTBClient)(nil).GetLatestPackageId), ctx, packageId, module)
}

// GetNormalizedModule mocks base method.
func (m *MockSuiPTBClient) GetNormalizedModule(ctx context.Context, packageId, moduleId string) (models.GetNormalizedMoveModuleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNormalizedModule", ctx, packageId, moduleId)
	ret0, _ := ret[0].(models.GetNormalizedMoveModuleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNormalizedModule indicates an expected call of GetNormalizedModule.
func (mr *MockSuiPTBClientMockRecorder) GetNormalizedModule(ctx, packageId, moduleId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNormalizedModule", reflect.TypeOf((*MockSuiPTBClient)(nil).GetNormalizedModule), ctx, packageId, moduleId)
}

// GetParentObjectID mocks base method.
func (m *MockSuiPTBClient) GetParentObjectID(ctx context.Context, packageID, moduleID, pointerObjectName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParentObjectID", ctx, packageID, moduleID, pointerObjectName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetParentObjectID indicates an expected call of GetParentObjectID.
func (mr *MockSuiPTBClientMockRecorder) GetParentObjectID(ctx, packageID, moduleID, pointerObjectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParentObjectID", reflect.TypeOf((*MockSuiPTBClient)(nil).GetParentObjectID), ctx, packageID, moduleID, pointerObjectName)
}

// GetSUIBalance mocks base method.
func (m *MockSuiPTBClient) GetSUIBalance(ctx context.Context, address string) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSUIBalance", ctx, address)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSUIBalance indicates an expected call of GetSUIBalance.
func (mr *MockSuiPTBClientMockRecorder) GetSUIBalance(ctx, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSUIBalance", reflect.TypeOf((*MockSuiPTBClient)(nil).GetSUIBalance), ctx, address)
}

// GetTransactionStatus mocks base method.
func (m *MockSuiPTBClient) GetTransactionStatus(ctx context.Context, digest string) (client.TransactionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionStatus", ctx, digest)
	ret0, _ := ret[0].(client.TransactionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionStatus indicates an expected call of GetTransactionStatus.
func (mr *MockSuiPTBClientMockRecorder) GetTransactionStatus(ctx, digest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionStatus", reflect.TypeOf((*MockSuiPTBClient)(nil).GetTransactionStatus), ctx, digest)
}

// GetValuesFromPackageOwnedObjectField mocks base method.
func (m *MockSuiPTBClient) GetValuesFromPackageOwnedObjectField(ctx context.Context, packageID, moduleID, objectName string, fieldKeys []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValuesFromPackageOwnedObjectField", ctx, packageID, moduleID, objectName, fieldKeys)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValuesFromPackageOwnedObjectField indicates an expected call of GetValuesFromPackageOwnedObjectField.
func (mr *MockSuiPTBClientMockRecorder) GetValuesFromPackageOwnedObjectField(ctx, packageID, moduleID, objectName, fieldKeys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValuesFromPackageOwnedObjectField", reflect.TypeOf((*MockSuiPTBClient)(nil).GetValuesFromPackageOwnedObjectField), ctx, packageID, moduleID, objectName, fieldKeys)
}

// HashTxBytes mocks base method.
func (m *MockSuiPTBClient) HashTxBytes(txBytes []byte) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashTxBytes", txBytes)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// HashTxBytes indicates an expected call of HashTxBytes.
func (mr *MockSuiPTBClientMockRecorder) HashTxBytes(txBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashTxBytes", reflect.TypeOf((*MockSuiPTBClient)(nil).HashTxBytes), txBytes)
}

// LoadModulePackageIds mocks base method.
func (m *MockSuiPTBClient) LoadModulePackageIds(ctx context.Context, packageId, module string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadModulePackageIds", ctx, packageId, module)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadModulePackageIds indicates an expected call of LoadModulePackageIds.
func (mr *MockSuiPTBClientMockRecorder) LoadModulePackageIds(ctx, packageId, module any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadModulePackageIds", reflect.TypeOf((*MockSuiPTBClient)(nil).LoadModulePackageIds), ctx, packageId, module)
}

// MoveCall mocks base method.
func (m *MockSuiPTBClient) MoveCall(ctx context.Context, req client.MoveCallRequest) (client.TxnMetaData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveCall", ctx, req)
	ret0, _ := ret[0].(client.TxnMetaData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveCall indicates an expected call of MoveCall.
func (mr *MockSuiPTBClientMockRecorder) MoveCall(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveCall", reflect.TypeOf((*MockSuiPTBClient)(nil).MoveCall), ctx, req)
}

// QueryEvents mocks base method.
func (m *MockSuiPTBClient) QueryEvents(ctx context.Context, filter client.EventFilterByMoveEventModule, limit *uint, cursor *client.EventId, sortOptions *client.QuerySortOptions) (*models.PaginatedEventsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryEvents", ctx, filter, limit, cursor, sortOptions)
	ret0, _ := ret[0].(*models.PaginatedEventsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryEvents indicates an expected call of QueryEvents.
func (mr *MockSuiPTBClientMockRecorder) QueryEvents(ctx, filter, limit, cursor, sortOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryEvents", reflect.TypeOf((*MockSuiPTBClient)(nil).QueryEvents), ctx, filter, limit, cursor, sortOptions)
}

// QueryTransactions mocks base method.
func (m *MockSuiPTBClient) QueryTransactions(ctx context.Context, fromAddress string, cursor *string, limit *uint64) (models.SuiXQueryTransactionBlocksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryTransactions", ctx, fromAddress, cursor, limit)
	ret0, _ := ret[0].(models.SuiXQueryTransactionBlocksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryTransactions indicates an expected call of QueryTransactions.
func (mr *MockSuiPTBClientMockRecorder) QueryTransactions(ctx, fromAddress, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryTransactions", reflect.TypeOf((*MockSuiPTBClient)(nil).QueryTransactions), ctx, fromAddress, cursor, limit)
}

// ReadFilterOwnedObjectIds mocks base method.
func (m *MockSuiPTBClient) ReadFilterOwnedObjectIds(ctx context.Context, ownerAddress, structType string, cursor string) ([]models.SuiObjectData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFilterOwnedObjectIds", ctx, ownerAddress, structType, cursor)
	ret0, _ := ret[0].([]models.SuiObjectData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFilterOwnedObjectIds indicates an expected call of ReadFilterOwnedObjectIds.
func (mr *MockSuiPTBClientMockRecorder) ReadFilterOwnedObjectIds(ctx, ownerAddress, structType, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFilterOwnedObjectIds", reflect.TypeOf((*MockSuiPTBClient)(nil).ReadFilterOwnedObjectIds), ctx, ownerAddress, structType, cursor)
}

// ReadFunction mocks base method.
func (m *MockSuiPTBClient) ReadFunction(ctx context.Context, signerAddress, packageId, module, function string, args []any, argTypes []string, typeArgs []string) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFunction", ctx, signerAddress, packageId, module, function, args, argTypes, typeArgs)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFunction indicates an expected call of ReadFunction.
func (mr *MockSuiPTBClientMockRecorder) ReadFunction(ctx, signerAddress, packageId, module, function, args, argTypes, typeArgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFunction", reflect.TypeOf((*MockSuiPTBClient)(nil).ReadFunction), ctx, signerAddress, packageId, module, function, args, argTypes, typeArgs)
}

// ReadObjectId mocks base method.
func (m *MockSuiPTBClient) ReadObjectId(ctx context.Context, objectId string) (models.SuiObjectData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadObjectId", ctx, objectId)
	ret0, _ := ret[0].(models.SuiObjectData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadObjectId indicates an expected call of ReadObjectId.
func (mr *MockSuiPTBClientMockRecorder) ReadObjectId(ctx, objectId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadObjectId", reflect.TypeOf((*MockSuiPTBClient)(nil).ReadObjectId), ctx, objectId)
}

// ReadOwnedObjects mocks base method.
func (m *MockSuiPTBClient) ReadOwnedObjects(ctx context.Context, ownerAddress string, cursor *models.ObjectId) ([]models.SuiObjectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadOwnedObjects", ctx, ownerAddress, cursor)
	ret0, _ := ret[0].([]models.SuiObjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadOwnedObjects indicates an expected call of ReadOwnedObjects.
func (mr *MockSuiPTBClientMockRecorder) ReadOwnedObjects(ctx, ownerAddress, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOwnedObjects", reflect.TypeOf((*MockSuiPTBClient)(nil).ReadOwnedObjects), ctx, ownerAddress, cursor)
}

// SendTransaction mocks base method.
func (m *MockSuiPTBClient) SendTransaction(ctx context.Context, payload client.TransactionBlockRequest) (client.SuiTransactionBlockResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTransaction", ctx, payload)
	ret0, _ := ret[0].(client.SuiTransactionBlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendTransaction indicates an expected call of SendTransaction.
func (mr *MockSuiPTBClientMockRecorder) SendTransaction(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTransaction", reflect.TypeOf((*MockSuiPTBClient)(nil).SendTransaction), ctx, payload)
}

// SetCachedValue mocks base method.
func (m *MockSuiPTBClient) SetCachedValue(key string, value any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCachedValue", key, value)
}

// SetCachedValue indicates an expected call of SetCachedValue.
func (mr *MockSuiPTBClientMockRecorder) SetCachedValue(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCachedValue", reflect.TypeOf((*MockSuiPTBClient)(nil).SetCachedValue), key, value)
}

// SetCachedValues mocks base method.
func (m *MockSuiPTBClient) SetCachedValues(keyValues map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCachedValues", keyValues)
}

// SetCachedValues indicates an expected call of SetCachedValues.
func (mr *MockSuiPTBClientMockRecorder) SetCachedValues(keyValues any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCachedValues", reflect.TypeOf((*MockSuiPTBClient)(nil).SetCachedValues), keyValues)
}

// SignAndSendTransaction mocks base method.
func (m *MockSuiPTBClient) SignAndSendTransaction(ctx context.Context, txBytesRaw string, signerPublicKey []byte, executionRequestType client.TransactionRequestType) (client.SuiTransactionBlockResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignAndSendTransaction", ctx, txBytesRaw, signerPublicKey, executionRequestType)
	ret0, _ := ret[0].(client.SuiTransactionBlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignAndSendTransaction indicates an expected call of SignAndSendTransaction.
func (mr *MockSuiPTBClientMockRecorder) SignAndSendTransaction(ctx, txBytesRaw, signerPublicKey, executionRequestType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignAndSendTransaction", reflect.TypeOf((*MockSuiPTBClient)(nil).SignAndSendTransaction), ctx, txBytesRaw, signerPublicKey, executionRequestType)
}

// GetReferenceGasPrice mocks base method.
func (m *MockSuiPTBClient) GetReferenceGasPrice(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReferenceGasPrice", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReferenceGasPrice indicates an expected call of GetReferenceGasPrice.
func (mr *MockSuiPTBClientMockRecorder) GetReferenceGasPrice(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReferenceGasPrice", reflect.TypeOf((*MockSuiPTBClient)(nil).GetReferenceGasPrice), ctx)
}

// GetLatestEpoch mocks base method.
func (m *MockSuiPTBClient) GetLatestEpoch(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestEpoch", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestEpoch indicates an expected call of GetLatestEpoch.
func (mr *MockSuiPTBClientMockRecorder) GetLatestEpoch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestEpoch", reflect.TypeOf((*MockSuiPTBClient)(nil).GetLatestEpoch), ctx)
}

// QueryCoinsByAddress mocks base method.
func (m *MockSuiPTBClient) QueryCoinsByAddress(ctx context.Context, address, coinType string) ([]models.CoinData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryCoinsByAddress", ctx, address, coinType)
	ret0, _ := ret[0].([]models.CoinData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryCoinsByAddress indicates an expected call of QueryCoinsByAddress.
func (mr *MockSuiPTBClientMockRecorder) QueryCoinsByAddress(ctx, address, coinType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCoinsByAddress", reflect.TypeOf((*MockSuiPTBClient)(nil).QueryCoinsByAddress), ctx, address, coinType)
}

// GetTokenPoolConfigByPackageAddress mocks base method.
func (m *MockSuiPTBClient) GetTokenPoolConfigByPackageAddress(ctx context.Context, accountAddress string, tokenPoolAddress string, ccipPackageAddress string) (module_token_admin_registry.TokenConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenPoolConfigByPackageAddress", ctx, accountAddress, tokenPoolAddress, ccipPackageAddress)
	ret0, _ := ret[0].(module_token_admin_registry.TokenConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenPoolConfigByPackageAddress indicates an expected call of GetTokenPoolConfigByPackageAddress.
func (mr *MockSuiPTBClientMockRecorder) GetTokenPoolConfigByPackageAddress(ctx, accountAddress, tokenPoolAddress, ccipPackageAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenPoolConfigByPackageAddress", reflect.TypeOf((*MockSuiPTBClient)(nil).GetTokenPoolConfigByPackageAddress), ctx, accountAddress, tokenPoolAddress, ccipPackageAddress)
}
