[package]
name = "MockChainlinkCCIPOnramp"
edition = "2024"

[addresses]
mock_ccip_v2 = "_"
mock_ccip_v2_onramp = "_"
mcms = "_"
mcms_owner = "_"

[dev-addresses]
mock_ccip_v2 = "0x1000"
mock_ccip_v2_onramp = "0x1001"
mcms = "0x4000"
mcms_owner = "0x4010"

[dependencies]
MockChainlinkCCIP = { local = "../mock_ccip_v2" }
ChainlinkManyChainMultisig = { local = "../../mcms/mcms" }
