[package]
name = "ChainlinkCCIP"
edition = "2024"

[addresses]
ccip = "_"
mcms = "_"
mcms_owner = "_"

[dev-addresses]
ccip = "0x1000"
mcms = "0x4000"
mcms_owner = "0x4010"

[dependencies]
ChainlinkManyChainMultisig = { local = "../../mcms/mcms" }