[package]
name = "TestModule"
edition = "2024.beta"

[dependencies]
ChainlinkManyChainMultisig = { local = "../../mcms/mcms" }

[addresses]
mcms_test = "_"
mcms = "_"
mcms_owner = "_"

[dev-addresses]
mcms_test = "0x0"
mcms = "0x999"
mcms_owner = "0x123"
