[package]
name = "TestModule"
edition = "2024.beta"

[dependencies]
ChainlinkManyChainMultisig = { local = "../../mcms/mcms" }

[addresses]
mcms_test = "_"
mcms = "_"

[dev-addresses]
# mcms = "0x40001"
mcms_test = "0x4900"
