name: Lint

on:
  pull_request:

permissions:
  contents: read

env:
  CONFIG_URL: https://raw.githubusercontent.com/smartcontractkit/chainlink/develop/.golangci.yml

jobs:
  golangci-lint:
    name: Lint Go files
    runs-on: ubuntu-latest

    env:
      REPORT_PATH: ${{ github.workspace }}/golangci-lint-report.xml

    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Download golangci-lint config
        run: curl -fsSL "${{ env.CONFIG_URL }}" -o .golangci.yml

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        # golangci-lint runs with absolute path mode: --path-mode=abs
        with:
          version: v2.1.6
          only-new-issues: true
          args: --output.checkstyle.path=${{ env.REPORT_PATH }}
          working-directory: ${{ github.workspace }}

      - name: Print lint report on failure
        if: failure()
        run: cat "${{ env.REPORT_PATH }}"

      - name: Upload lint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: golangci-lint-report
          path: ${{ env.REPORT_PATH }}

  ci-lint-misc:
    name: Lint GH Actions and scripts
    runs-on: ubuntu-latest
    steps:
      - name: Lint Misc (yaml + sh files)
        uses: smartcontractkit/.github/actions/ci-lint-misc@01d931b0455a754d12e7143cc54a5a3521a8f6f6 # ci-lint-misc@0.1.4
