name: pull-request-main

on:
  pull_request:
    branches:
      - main

jobs:
  ci-lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: smartcontractkit/.github/actions/setup-nix@01d931b0455a754d12e7143cc54a5a3521a8f6f6 # setup-nix@0.3.2

      - name: Run GolangCI Lint
        run: |
          nix develop --command task lint

  ci-lint-misc:
    name: Lint GH Actions and scripts
    runs-on: ubuntu-latest
    steps:
      - name: Lint Misc (yaml + sh files)
        uses: smartcontractkit/.github/actions/ci-lint-misc@01d931b0455a754d12e7143cc54a5a3521a8f6f6 # ci-lint-misc@0.1.4

  ci-test:
    name: Go Test - Unit and Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: smartcontractkit/.github/actions/setup-nix@01d931b0455a754d12e7143cc54a5a3521a8f6f6 # setup-nix@0.3.2

      - name: Run GolangCI Lint
        run: |
          nix develop --command task test
