name: pull-request-main

on:
  merge_group:
  pull_request:
    branches:
      - main

jobs:
  ci-lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Linting Go
        uses: smartcontractkit/.github/actions/ci-lint-go@01d931b0455a754d12e7143cc54a5a3521a8f6f6 # ci-lint-go@0.3.1
        with:
          golangci-lint-version: v1.64.8

  ci-lint-misc:
    name: Lint GH Actions and scripts
    runs-on: ubuntu-latest
    steps:
      - name: Linting Misc (yaml + sh files)
        uses: smartcontractkit/.github/actions/ci-lint-misc@01d931b0455a754d12e7143cc54a5a3521a8f6f6 # ci-lint-misc@0.1.4

  ci-test:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Build and test
        uses: smartcontractkit/.github/actions/ci-test-go@ci-test-go/0.3.5
        with:
          go-test-cmd: go test -coverprofile=coverage.txt $(go list ./...)
          use-go-cache: true
