[package]
name = "ChainlinkCCIPOfframp"
edition = "2024"

[addresses]
ccip_offramp = "0x0"

[dependencies]
ChainlinkCCIP = { local = "../ccip" }
ChainlinkManyChainMultisig = { local = "../../mcms/mcms" }
