[package]
name = "ChainlinkCCIPOfframp"
edition = "2024"
published-at = "0xdec6eef8180d0a62a1dab9182c28bb854cfe0cf013d24344c3e6cb3de6b10572"

[addresses]
ccip = "_"
ccip_offramp = "0x0"
mcms = "_"
mcms_owner = "_"

[dev-addresses]
ccip = "0x1000"
ccip_offramp = "0x1001"
mcms = "0x4000"
mcms_owner = "0x4010"

[dependencies]
ChainlinkCCIP = { local = "../ccip" }
ChainlinkManyChainMultisig = { local = "../../mcms/mcms" }
