[package]
name = "ChainlinkCCIPOfframp"
edition = "2024.beta"

[addresses]
ccip = "_"
ccip_offramp = "_"
mcms = "_"
mcms_owner = "_"
mcms_register_entrypoints = "_"

[dev-addresses]
ccip = "0x1000"
ccip_offramp = "0x1001"
mcms = "0x4000"
mcms_owner = "0x4010"
mcms_register_entrypoints = "0x4001"

[dependencies]
ChainlinkCCIP = { local = "../ccip" }
