[package]
name = "ChainlinkCCIPOfframp"
edition = "2024"
published-at = "0x01a0a22b2abacbd48e9a026c1661189a8ec5ce4942cba07017b63eaad0a205a4"

[addresses]
ccip = "_"
ccip_offramp = "0x0"
mcms = "_"
mcms_owner = "_"

[dev-addresses]
ccip = "0x1000"
ccip_offramp = "0x1001"
mcms = "0x4000"
mcms_owner = "0x4010"

[dependencies]
ChainlinkCCIP = { local = "../ccip" }
ChainlinkManyChainMultisig = { local = "../../mcms/mcms" }
